const qs=new URLSearchParams(location.search),movie=qs.get("movie"),room=qs.get("room"),isOwner=qs.get("owner")==="1";
const video=document.getElementById("video"),roleEl=document.getElementById("role"),roomEl=document.getElementById("roomLabel"),movieNameEl=document.getElementById("movieName"),inviteEl=document.getElementById("invite"),copyBtn=document.getElementById("copyBtn"),syncBtn=document.getElementById("syncBtn");
if(!movie||!room){alert("Missing room or movie");location.href="./index.html";}
video.src=movie;movieNameEl.textContent=decodeURIComponent(movie.split("/").pop());roomEl.textContent=`Room: ${room}`;roleEl.textContent=isOwner?"Owner":"Viewer";
const ownerPeerId=`solarflix-${room}-owner`,viewerPeerId=`solarflix-${room}-viewer-${Math.random().toString(36).slice(2,8)}`,inviteURL=`${location.origin}${location.pathname}?movie=${encodeURIComponent(movie)}&room=${encodeURIComponent(room)}`;
inviteEl.textContent=inviteURL;copyBtn.onclick=async()=>{try{await navigator.clipboard.writeText(inviteURL);copyBtn.textContent="Copied";setTimeout(()=>copyBtn.textContent="Copy Invite",1200)}catch{alert("Copy failed")}};
let peer,conns=[],ownerConn=null,applyingRemote=false;
function statePayload(type="sync"){return{t:type,paused:video.paused,currentTime:video.currentTime,playbackRate:video.playbackRate,ts:Date.now()}}
function applyState(msg){if(!msg)return;applyingRemote=true;const drift=Math.abs((video.currentTime||0)-(msg.currentTime||0));if(drift>0.8)video.currentTime=msg.currentTime||0;video.playbackRate=msg.playbackRate||1;if(msg.paused)video.pause();else video.play().catch(()=>{});setTimeout(()=>applyingRemote=false,50)}
if(isOwner){peer=new Peer(ownerPeerId);peer.on("connection",conn=>{conns.push(conn);conn.on("open",()=>conn.send(statePayload("sync")));conn.on("close",()=>conns=conns.filter(c=>c!==conn))});const broadcast=p=>conns.forEach(c=>c.open&&c.send(p));["play","pause","seeking","ratechange"].forEach(ev=>video.addEventListener(ev,()=>{if(applyingRemote)return;broadcast(statePayload(ev))}));const timer=setInterval(()=>broadcast(statePayload("heartbeat")),2000);window.addEventListener("beforeunload",()=>clearInterval(timer));syncBtn.onclick=()=>broadcast(statePayload("force"));}
else{peer=new Peer(viewerPeerId);peer.on("open",()=>{ownerConn=peer.connect(ownerPeerId,{reliable:true});ownerConn.on("open",()=>ownerConn.send({t:"hello"}));ownerConn.on("data",msg=>applyState(msg));});["play","pause","seeking","ratechange"].forEach(ev=>video.addEventListener(ev,()=>{if(!applyingRemote)ownerConn&&ownerConn.send({t:"requestSync"})}));syncBtn.onclick=()=>ownerConn&&ownerConn.send({t:"requestSync"});}
